Kelompok 1
andrisan-ub/paw-c-2022 pull request #13
Opened 2022-09-21 15:37 UTC by asyamadil2

2022-09-22 02:37 UTC, faridefendi44 commented
fix issues #1

2022-09-30 02:11 UTC, andrisan-ub commented
Buat folder untuk kelompok, dan pindahkan semua file ke folder tersebut.

2022-09-30 02:18 UTC, andrisan-ub requested changes
Buat folder untuk kelompok, dan pindahkan semua file ke folder tersebut.

2022-10-05 07:03 UTC, faridefendi44 commented
Folder Kelompok 1 done #13

2022-10-10 09:47 UTC, andrisan-ub approved these changes

2022-10-10 09:47 UTC, merged